# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/rank-bert',
                'doc_host': 'https://numb3r33.github.io',
                'git_url': 'https://github.com/numb3r33/rank-bert',
                'lib_path': 'rank_bert'},
  'syms': {'rank_bert.core': {'rank_bert.core.foo': ('core.html#foo', 'rank_bert/core.py')}}}
